apiVersion: v1
kind: ConfigMap
metadata:
  name: product-feedback-bff-config
data:
  ASPNETCORE_HTTP_PORTS: "5185"
  ASPNETCORE_URLS: "http://+:5185"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  ForwardedHeaders__KnownNetworks__0: "10.244.0.0/16"
  ReverseProxy__Clusters__product-feedback-api__Destinations__destination1__Address: "http://product-feedback-api-svc.product-feedback.svc.cluster.local:5185/"
  ConnectionStrings__RedisConnection: "redis-master.redis.svc.cluster.local:6379"
  KEYCLOAK_SERVER_URL: "https://identity.alexbartleynees.com"
  OpenIdConnectOptions__ClientSecret: ${CLIENT_SECRET}
  OpenIdConnectOptions__RedirectUri: https://product-feedback.alexbartleynees.com/signin-oidc
  Redis__UseTls: "true"
  Redis__Host: "redis-master.redis.svc.cluster.local"
